import FullLayout from "../src/layouts/FullLayout";
import Head from "next/head";
import "../styles/style.scss";

//import { useState } from "react";
function MyApp({ Component, pageProps }) {


  return (
    <>
      <Head>
        <title> Contact DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/appimg/ContactDBApp/favicon.ico" />
      </Head>
      
     
      <FullLayout>
        <Component {...pageProps} />

     
      </FullLayout> 

      
    </>
  );
}

export default MyApp;
