import Head from "next/head";
import { Col, Row } from "reactstrap";
import SalesChart from "../src/components/dashboard/SalesChart";
import Feeds from "../src/components/dashboard/Feeds";
import ProjectTables from "../src/components/dashboard/ProjectTable";
import TopCards from "../src/components/dashboard/TopCards";
import ReportTables from "../src/components/dashboard/ReportTable";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contact DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        

      </Head>
      <div>
        {/***Top Cards***/}
        <Row>
           <Col sm="6" lg="4">
            <TopCards
              bg="bg-light-success text-success"
              title="Profit"
              //subtitle="Organisation"
              earning="Organisation"
              icon="bi bi-wallet"
            />
          </Col>
          <Col sm="6" lg="4">
            <TopCards
              bg="bg-light-danger text-danger"
              title="Refunds"
              //subtitle="Contact"
              earning="Contact"
              icon="bi bi-person"
            />
          </Col>
          <Col sm="6" lg="4">
            <TopCards
              bg="bg-light-warning text-warning"
              title="New Project"
              //subtitle="Upcoming Event"
              earning="Upcoming Event"
              icon="bi bi-calendar3"
            />
          </Col> 
          {/* <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-info text-into"
              title="Sales"
              subtitle="Weekly Sales"
              earning="210"
              icon="bi bi-bag"
            />
          </Col>  */}
        </Row> 
       
        {/***Sales & Feed***/}
        <Row>
           {/* <Col sm="12" lg="6" xl="7" xxl="4">
            <SalesChart />
          </Col> */}
          <Col sm="12" lg="6" xl="7" xxl="8">
            
          </Col> 
          <Col sm="12" lg="6" xl="6" xxl="4">
            <Feeds />
          </Col> 


        </Row> 


        {/***Table ***/}
        <Row>
          <Col lg="12" sm="12">
            {/* <ProjectTables /> */}
            <ReportTables />
          </Col>
        </Row>
        
      </div>
    </div>
  );
}
